export const NAVIGATION = 'NAVIGATION';
export const LOGIN = 'LOGIN';
export const PRODUCT_LIST = 'PRODUCT_LIST';
export const PRODUCT_DETAILS = 'PRODUCT_DETAILS';

export const LOGIN_CHANGE_EMAIL = 'LOGIN_CHANGE_EMAIL';
export const LOGIN_CHANGE_PASSWORD = 'LOGIN_CHANGE_PASSWORD';
export const LOGIN_RESET_DATA = 'LOGIN_RESET_DATA';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_ERROR_HIDE = 'LOGIN_ERROR_HIDE';
export const USER_LOGED_IN = 'USER_LOGED_IN';
export const LOGIN_ERROR_EMPTY_FIELDS = "LOGIN_ERROR_EMPTY_FIELDS";
export const LOGIN_ERROR_WRONG_FIELDS = "LOGIN_ERROR_WRONG_FIELDS";
export const LOGIN_START_LOGIN = "LOGIN_START_LOGIN";
export const LOGIN_NO_NETWORK = "LOGIN_NO_NETWORK";

export const PRODUCT_LIST_REINIT = 'PRODUCT_LIST_REINIT';
export const PRODUCT_LIST_UPDATE_LIST = 'PRODUCT_LIST_UPDATE_LIST';
export const PRODUCT_LIST_START_LOADING_NEXT_PAGE = 'PRODUCT_LIST_START_LOADING_NEXT_PAGE';
export const PRODUCT_LIST_START_REINIT = 'PRODUCT_LIST_START_REINIT';