export const NAVIGATION = 'NAVIGATION';
export const LOGIN = 'LOGIN';
export const PRODUCT_LIST = 'PRODUCT_LIST';
export const PRODUCT_DETAILS = 'PRODUCT_DETAILS';

export const LOGIN_CHANGE_EMAIL = 'LOGIN_CHANGE_EMAIL';
export const LOGIN_CHANGE_PASSWORD = 'LOGIN_CHANGE_PASSWORD';
export const LOGIN_RESET_DATA = 'LOGIN_RESET_DATA';