export const NAVIGATION = 'NAVIGATION';
export const LOGIN = 'LOGIN';
export const PRODUCT_LIST = 'PRODUCT_LIST';
export const PRODUCT_DETAILS = 'PRODUCT_DETAILS';

export const LOGIN_CHANGE_EMAIL = 'LOGIN_CHANGE_EMAIL';
export const LOGIN_CHANGE_PASSWORD = 'LOGIN_CHANGE_PASSWORD';
export const LOGIN_RESET_DATA = 'LOGIN_RESET_DATA';
export const USER_LOGED_IN = 'USER_LOGED_IN';

export const PRODUCT_LIST_REINIT = 'PRODUCT_LIST_REINIT';
export const PRODUCT_LIST_UPDATE_LIST = 'PRODUCT_LIST_UPDATE_LIST';
export const PRODUCT_LIST_START_LOADING_NEXT_PAGE = 'PRODUCT_LIST_START_LOADING_NEXT_PAGE';
export const PRODUCT_LIST_START_REINIT = 'PRODUCT_LIST_START_REINIT';